### PR TITLE
bugfix in fillColor

### PR DESCRIPTION
**Pull request by nihimoto**
Hello.
Please check this.

### CODE REVIEW

**Comment by johanbove** [comment]
Thanks Nihimoto for your help with this.
Can you please add a test to prove this is working?

**Comment by nihimoto** [comment]
I can't understand What you want.
"test" ? test code?

My test is next screen shot.

before:


after:

**Comment by johanbove** [comment]
Perfect. A screenshot is good to show that this works. Thank you!

**Comment by nihimoto** [comment]
thank you !!

**Pull request merged**
