### PR TITLE
Changes made to incorporate an array of values for FillBetweenLines f…

### PR DESCRIPTION
**Pull request by johncant**
…unctionality

Hi!

I've ported a pull request from Bitbucket that allows you to fill between multiple pairs of series. It works.

https://bitbucket.org/cleonello/jqplot/pull-requests/51/changes-made-to-incorporate-an-array-of/diff

I take no credit - the author of this pull request is gyandeeps

### CODE REVIEW

**Comment by gyandeeps** [comment]
Feel free to merge this as I already did this in my repo of jqplot: https://github.com/gyandeeps/JqPlot

**Comment by johanbove** [comment]
@gyandeeps Thanks for the PR. Sorry for the late reply. Can you please add an example how this can be used, so we can verify this still works in the latest changes? Thanks!

**Comment by gyandeeps** [comment]
I sent this PR to bitbucket but it was ported to this place by @johncant . I cant make changes into this PR but I can share an example in comment if you want?

**Comment by gyandeeps** [comment]
```js
$(document).ready(function(){
    var l0 = [6,  11, 10, 13, 11,  7];
    var l1 = [3,   6,  7,  7,  5,  3];
    var l2 = [4,   8,  9, 10, 8,   6];
    var l3 = [9,  13, 14, 16, 17, 19];
    var l4 = [15, 17, 16, 18, 13, 11];
     
    var plot1 = $.jqplot("chart1", [l0, l1, l2, l3, l4], {
        title: "Fill between 2 lines",
        axesDefaults: {
            pad: 1.05
        },
        //////
        // Use the fillBetween option to control fill between two
        // lines on a plot.
        //////
        fillBetween: {
            // series1: Required, if missing won't fill.
            series1: [1, 3],
            // series2: Required, if  missing won't fill.
            series2: [2, 4],
            // color: Optional, defaults to fillColor of series1.
            color: "rgba(227, 167, 111, 0.7)",
            // baseSeries:  Optional.  Put fill on a layer below this series
            // index.  Defaults to 0 (first series).  If an index higher than 0 is
            // used, fill will hide series below it.
            baseSeries: 0,
            // fill:  Optional, defaults to true.  False to turn off fill.  
            fill: true
        },
        seriesDefaults: {
            rendererOptions: {
                //////
                // Turn on line smoothing.  By default, a constrained cubic spline
                // interpolation algorithm is used which will not overshoot or
                // undershoot any data points.
                //////
                smooth: true
            }
        }
    });
 
    // bind a function to the change button to update the plot's fillBetween series
    // and replot().
    $("button[name=changeFill]").click(function(e) {
        plot1.fillBetween.series1 = parseInt($("input[name=series1]").val());
        plot1.fillBetween.series2 = parseInt($("input[name=series2]").val());
        plot1.replot();
    });
});
```

I took the above example from [here](http://www.jqplot.com/examples/fillBetweenLines.php) and modified it.
With the modification it will fill between
* Series 1 and 2
* Series 3 and 4

**Comment by johanbove** [comment]
Thanks for the example. I'm currently adapting the "changeFill" function so it also accepts the arrays of values.

**Comment by johncant** [comment]
@gyandeeps - you can submit a pull request on a pull request!

**Comment by gyandeeps** [comment]
The change I made above is backward compatible ie even if you use it in the old way by passing in just a number than also it works.

**Comment by gyandeeps** [comment]
Here is the screenshot: 
image

**Comment by johanbove** [comment]
Thanks for the help. I've merged your changes.

**Comment by phacUNC** [comment]
This is exactly what I have been looking for! Thank you. In which version of jqplot will this be available?
Suggestion, how about supporting an array for the color property as well, so the second fill can be distinguished from the first one.

**Comment by johncant** [comment]
@phacUNC , any version after 1.0.8. You might be better of using this repository though. You can specify 0 and get the same colour as the first series in each pair. If that doesn't meet your needs, then you should find it quite easy to implement the feature you need.

**Pull request merged**
