### PR TITLE
Massive merge

### PR DESCRIPTION
**Pull request by johanbove**
Pull request to integrate my changes:
- For issue #10 
- Using Git information in the build.xml
- Added features: new canvas elements to canvasOverlay
- Added examples
- Various bug fixes

Currently one big pull request since I already merged the branches and Github tells me it is able to merge :smile:

Please review.

### CODE REVIEW

**Comment by johanbove** [comment]
@ppritcha I realize this might a lot of work, but can you verify this pull request please? Thanks!

**Comment by ppritcha** [comment]
Yes, I will work on it in the next couple of days.

**Comment by ppritcha** [comment]
Johan, I tested the "massive merge" using my low-tech testing method, which compares screenshots of the 56 example pages before and after the changes.  There were no problems.

I merged the pull request into the refactoring branch.  Any reason we should not merge this into the master branch now? I'd like to incorporate your changes into the 1.0.9 release.

**Comment by johanbove** [comment]
Glad to hear there were no issues with your "low-tech" testing method.
Seems like it would fit a 1.0.9 release since not much new functionality
was added.
Perhaps I should compile a change list first so we can document what was
changed?

On Tue, Oct 13, 2015 at 8:59 PM, Paul Pritchard <notifications@github.com>
wrote:

> Johan, I tested the "massive merge" using my low-tech testing method,
> which compares screenshots of the 56 example pages before and after the
> changes. There were no problems.
>
> I merged the pull request into the refactoring branch. Any reason we
> should not merge this into the master branch now? I'd like to incorporate
> your changes into the 1.0.9 release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jqPlot/jqPlot/pull/11#issuecomment-147814271>.
>



-- 
Johan

--
http://johanbove.info

**Comment by ppritcha** [comment]
Yes, please compile a change list.  That would be very helpful.

**Comment by johanbove** [comment]
Hi. Most changes were made to make the code follow "JSlint" rules. Since there were a lot of changes, the best "changelog" I can actually give is this GitHub comparison. 
<https://github.com/jqPlot/jqPlot/compare/master...jqPlot:refactoring> 

Did you run into any issues when checking out the "refactoring" branch code?

**Pull request merged**
