### PR TITLE
fix for #47 (donut charts not rendering correctly because of highres support)

### PR DESCRIPTION
**Pull request by jeschr**
canvas.style.width and canvas.style.height must be used instead of canvas.width and canvas.height

### CODE REVIEW

**Comment by johanbove** [comment]
Thanks for the quick fix. Seems to be fine now. :star:

**Comment by bulldozier** [comment]
There is still a bug related to canvasBackingScale. Whenever canvasBackingScale is set to a value other than 1, pie charts render incorrectly, essentially used the scaled width and height to draw the pie graph, but with everything else using the non-scaled width and height. When the canvasBackingScale is set to 1 (which is the case most of the time), you get this:

`
<canvas width="300" height="205" class="jqplot-base-canvas" style="position: absolute; left: 0px; top: 0px; width: 300px; height: 205px;"></canvas>
`

But when canvasBackingScale=2, which happens for iPhones and high-res mac monitors, you get this:

`
<canvas width="600" height="410" class="jqplot-base-canvas" style="position: absolute; left: 0px; top: 0px; width: 300px; height: 205px;"></canvas>
`

Whenever the latter occurs, exporting to PNG will make the chart twice as big as it should be, with the legend and labels having the correct size.

**Comment by johanbove** [comment]
Hi @bulldozier, thanks for testing this. Could you provide a fix for the canvasBackingScale issue please? That would be awesome. As you might have guessed, I no longer have much time available for this project and it would be great if the main repo for jQPlot could attract more active developers. Are you in? Cheers.

**Comment by harryzhux** [comment]
I am @bulldozier's colleague and worked with him on this issue. You can merge the fixes from my fork https://github.com/harryzhux/jqPlot or give me permission to checkin into the main repository. Thanks

**Comment by harryzhux** [comment]
Committed the fix.
I use below as an example to test the bug and verify the fix.
It gives the incorrect scaled image (using the jqplot cdn.)
After rebuild jqplot with the fix, the image has the correct scale.

```
<!DOCTYPE>
<html>
<head>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqPlot/1.0.9/jquery.jqplot.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqPlot/1.0.9/plugins/jqplot.pieRenderer.js"></script>
<link rel="stylesheet" type="text/css" hrf="https://cdnjs.cloudflare.com/ajax/libs/jqPlot/1.0.9/jquery.jqplot.min.css"
/>
<title></title>
</head>
<body>
Plot:
<div id="chart" style="width: 600px; height: 300px;"></div>

Image:
<div id="imgChart"></div>

<script type="text/javascript">
$(document).ready(function(){
  var data = [
    ['Heavy Industry', 12],['Retail', 9], ['Light Industry', 14],
    ['Out of home', 16],['Commuting', 7], ['Orientation', 9]
  ];
  var plot1 = jQuery.jqplot ('chart', [data],
    {
      seriesDefaults: {
        // Make this a pie chart.
        renderer: jQuery.jqplot.PieRenderer,
        rendererOptions: {
          // Put data labels on the pie slices.
          // By default, labels show the percentage of the slice.
          showDataLabels: true
        }
      }, 
      legend: { show:true, location: 'e' }
    }
  );
  var imgData = $('#chart').jqplotToImageStr({});
  var imgElem = $('<img/>').attr('src',imgData);
  $('#imgChart').append(imgElem);
});
</script>
</body>
</html>
```

**Comment by nicknaam** [comment]
I have used the above script in jsfiddle to see if the rendering is fixed. But the images is not rendered correctly in a High res screens.
image

**Comment by harryzhux** [comment]
Please notice the script is to report/demo the problem, which uses the
published version (1.0.9) of the jqplot.
The fix has checked-in into the codebase, you need clone the repository and
compile the code to get a unofficial version of jqplot and modify the
script to link to it to see correctly rendered High res charts.

Harry

**Pull request merged**
